---
configure_terminal: true
configure_dotfiles: true
configure_dock: true
configure_browser: true
configure_defaults: true
configure_backup: true

configure_spotlight: false

setup_repo: https://github.com/lb3dev/ansible-macos-setup
setup_repo_version: master

backup_repo: https://github.com/lb3dev/ansible-macos-backup
backup_repo_version: f671e6bf72bc9ce8d0636b87ed301314e5cf3e93

dotfiles_repo: https://github.com/lb3dev/dotfiles.git
dotfiles_repo_version: 3c9d953daf766f8fab543e007656add8cf0f417b
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.setup/dotfiles
dotfiles_files:
  - .zshrc

homebrew_taps: []

homebrew_installed_packages:
  - dockutil
  - jq
  - ffmpeg
  - yt-dlp
  - rdiff-backup

homebrew_cask_apps:
  - android-file-transfer
  - sublime-text
  - keepassxc
  - firefox
  - google-chrome
  - pycharm-ce
  - utm

dockutil_install: false
dockitems_remove:
  - 'Launchpad'
  - 'Messages'
  - 'Mail'
  - 'Maps'
  - 'Photos'
  - 'FaceTime'
  - 'Contacts'
  - 'Reminders'
  - 'Notes'
  - 'TV'
  - 'Music'
  - 'Podcasts'
  - 'News'
  - 'App Store'
  - 'Freeform'

dockitems_persist: []
dockitems_starting_pos: 1
dockitems_persist_items:
  - name: 'Calendar'
    path: '/System/Applications/Calendar.app'
  - name: 'Android File Transfer'
    path: '/Applications/Android File Transfer.app'
  - name: 'Safari'
    path: '/Applications/Safari.app'
  - name: 'Firefox'
    path: '/Applications/Firefox.app'
  - name: 'Google Chrome'
    path: '/Applications/Google Chrome.app'
  - name: 'KeePassXC'
    path: '/Applications/KeePassXC.app'
  - name: 'Sublime Text'
    path: '/Applications/Sublime Text.app'
  - name: 'PyCharm CE'
    path: '/Applications/PyCharm CE.app'
  - name: 'Terminal'
    path: '/System/Applications/Utilities/Terminal.app'
  - name: 'UTM'
    path: '/Applications/UTM.app'
  - name: 'Activity Monitor'
    path: '/System/Applications/Utilities/Activity Monitor.app'
  - name: 'Disk Utility'
    path: '/System/Applications/Utilities/Disk Utility.app'
  - name: 'System Settings'
    path: '/System/Applications/System Settings.app'

no_xcode_install: true
spotlight_index_items:
  - '{"enabled" = 1;"name" = "APPLICATIONS";}'
  - '{"enabled" = 0;"name" = "MENU_EXPRESSION";}'
  - '{"enabled" = 0;"name" = "CONTACT";}'
  - '{"enabled" = 0;"name" = "MENU_CONVERSION";}'
  - '{"enabled" = 0;"name" = "MENU_DEFINITION";}'
  - '{"enabled" = 0;"name" = "SOURCE";}'
  - '{"enabled" = 0;"name" = "DOCUMENTS";}'
  - '{"enabled" = 0;"name" = "EVENT_TODO";}'
  - '{"enabled" = 0;"name" = "DIRECTORIES";}'
  - '{"enabled" = 0;"name" = "FONTS";}'
  - '{"enabled" = 0;"name" = "IMAGES";}'
  - '{"enabled" = 0;"name" = "MESSAGES";}'
  - '{"enabled" = 0;"name" = "MOVIES";}'
  - '{"enabled" = 0;"name" = "MUSIC";}'
  - '{"enabled" = 0;"name" = "MENU_OTHER";}'
  - '{"enabled" = 0;"name" = "PDF";}'
  - '{"enabled" = 0;"name" = "PRESENTATIONS";}'
  - '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
  - '{"enabled" = 0;"name" = "SPREADSHEETS";}'
  - '{"enabled" = 1;"name" = "SYSTEM_PREFS";}'
  - '{"enabled" = 0;"name" = "TIPS";}'
  - '{"enabled" = 0;"name" = "BOOKMARKS";}'

# Restrict Spotlight to only index Applications and System Preferences
spotlight_defaults: {domain: com.apple.Spotlight, key: orderedItems, type: array, value: "{{ spotlight_index_items }}"}

osx_defaults:
  ## General UI

  # Always expand Save UI panels
  - {domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true}
  # Save to disk (not to iCloud) by default
  - {domain: NSGlobalDomain, key: NSDocumentSaveNewDocumentsToCloud, type: bool, value: false}
  # Always show scroll bars (WhenScrolling, Automatic and Always)
  - {domain: NSGlobalDomain, key: AppleShowScrollBars, type: string, value: Always}
  # Expand Save panels
  - {domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true}
  - {domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true}
  # Expand print panels
  - {domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint, type: bool, value: true}
  - {domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint2, type: bool, value: true}

  ## Mouse / Pointer

  # Disable Natural Scroll for mice
  - {domain: NSGlobalDomain, key: com.apple.swipescrolldirection, type: bool, value: false}
  # Disable mouse acceleration, linear curve
  - {domain: NSGlobalDomain, key: com.apple.mouse.linear, type: bool, value: true}

  ## Keyboard / Input

  # Set fastest Key Repeat
  - {domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2}
  # Set faster initial Delay Util Repeat
  - {domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 25}
  # Disable auto capitalization
  - {domain: NSGlobalDomain, key: NSAutomaticCapitalizationEnabled, type: bool, value: false}
  # Disable smart dashes
  - {domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false}
  # Disable period substitution
  - {domain: NSGlobalDomain, key: NSAutomaticPeriodSubstitutionEnabled, type: bool, value: false}
  # Disable smart quotes
  - {domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false}

  ## Finder

  # Show all file extensions
  - {domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: true}
  # Disable delay for title view
  - {domain: NSGlobalDomain, key: NSToolbarTitleViewRolloverDelay, type: float, value: 0}
  # Show all hidden files
  - {domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true}
  # Set default opening view to Documents folder
  - {domain: com.apple.finder, key: NewWindowTarget, type: string, value: PfDo}
  # Enable Quit Finder option in menu (also enables Cmd + Q for Finder)
  - {domain: com.apple.finder, key: QuitMenuItem, type: bool, value: true}
  # Show status bar at the bottom
  - {domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true}
  # Show path bar at the bottom
  - {domain: com.apple.finder, key: ShowPathbar, type: bool, value: true}
  # Default to list view
  - {domain: com.apple.finder, key: FXPreferredViewStyle, type: string, value: Nlsv}
  # Keep folders above files
  - {domain: com.apple.finder, key: _FXSortFoldersFirst, type: bool, value: true}
  # Search the current folder by default rather than full system
  - {domain: com.apple.finder, key: FXDefaultSearchScope, type: string, value: SCcf}
  # Disable warning dialog when changing file extensions
  - {domain: com.apple.finder, key: FXEnableExtensionChangeWarning, type: bool, value: false}
  # Avoid creating .DS_Store files on network volumes
  - {domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: true}
  # Avoid creating .DS_Store files on USB volumes
  - {domain: com.apple.desktopservices, key: DSDontWriteUSBStores, type: bool, value: true}

  ## Dock

  # Set default Dock icon size
  - {domain: com.apple.dock, key: tilesize, type: float, value: 70}
  # Lock Dock icon size
  - {domain: com.apple.dock, key: size-immutable, type: bool, value: true}
  # Remove Recent Applications from Dock
  - {domain: com.apple.dock, key: show-recents, type: bool, value: false}

  ## Activity Monitor

  # Show All Processes instead of My Processes by default
  - {domain: com.apple.ActivityMonitor, key: ShowCategory, type: int, value: 0}
  # Change update frequency to Often (2 seconds)
  - {domain: com.apple.ActivityMonitor, key: UpdatePeriod, type: int, value: 2}
  # Change dock icon to show current CPU usage graph
  - {domain: com.apple.ActivityMonitor, key: IconType, type: int, value: 5}
