---
- hosts: all
  vars_files:
    - default.config.yml
  roles:
    - role: terminal
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      tags: ['dock']
  tasks:
    - import_tasks: tasks/osx_defaults.yml
    - import_tasks: tasks/osx_script.yml
    - import_tasks: tasks/backup.yml
