---
- hosts: all
  vars_files:
    - default.config.yml
  vars_prompt:
    - name: initial_setup_var
      prompt: Run full initial setup (browser open pages, macOS defaults)? (Y/n)
  pre_tasks:
    - name: Set initial setup variable
      set_fact:
        initial_setup: "{{ initial_setup_var == 'y' or initial_setup_var == 'Y' }}"
    - name: Update dockitems_persist_items with pos numbers
      set_fact:
        dockitems_persist: "{{ dockitems_persist | default([]) + [{ 'name': item.name, 'path': item.path, 'pos': dockitems_starting_pos | int }] }}"
        dockitems_starting_pos: "{{ dockitems_starting_pos | int + 1 }}"
      with_items: "{{ dockitems_persist_items | default([]) }}"
    - name: Display dockitems_persist
      debug:
        msg: ""
      with_items: "{{ dockitems_persist }}"
  roles:
    - role: terminal
      when: configure_terminal
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: browser
      when: configure_browser
  tasks:
    - import_tasks: tasks/osx_defaults.yml
      when: configure_defaults
    - import_tasks: tasks/spotlight.yml
    - import_tasks: tasks/backup.yml
      when: configure_backup
