---
- hosts: all
  vars_files:
    - default.config.yml
  vars_prompt:
    - name: initial_setup_var
      prompt: Run full initial setup (browser open pages, macOS defaults)? (Y/n)
  pre_tasks:
    - name: Set initial setup variable
      set_fact:
        initial_setup: "{{ initial_setup_var == 'y' or initial_setup_var == 'Y' }}"
  roles:
    - role: terminal
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: ansible_become_password is defined and ansible_become_password != ''
    - role: geerlingguy.mac.dock
      tags: ['dock']
      when: ansible_become_password is defined and ansible_become_password != ''
    - role: browser
  tasks:
    - import_tasks: tasks/osx_defaults.yml
      when: ansible_become_password is defined and ansible_become_password != ''
    - import_tasks: tasks/osx_script.yml
      when: ansible_become_password is defined and ansible_become_password != ''
    - import_tasks: tasks/backup.yml
