---
- hosts: all
  vars_files:
    - default.config.yml
  vars_prompt:
    - name: ansible_become_password
      prompt: Please enter sudo password (used for become, homebrew)
      private: yes
  pre_tasks:
    - name: Set homebrew sudo password
      set_fact:
        homebrew_cask_sudo_password: "{{ ansible_become_password }}"
  roles:
    - role: terminal
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      tags: ['dock']
    - role: browser
  tasks:
    - import_tasks: tasks/osx_defaults.yml
    - import_tasks: tasks/osx_script.yml
    - import_tasks: tasks/backup.yml
