---
- name: Git checkout setup repo
  git:
    repo: "{{ setup_repo }}"
    dest: "{{ ansible_env.HOME + '/.setup/ansible-macos-setup' }}"
    version: "{{ setup_repo_version }}"

- name: Git checkout backup repo
  git:
    repo: "{{ backup_repo }}"
    dest: "{{ ansible_env.HOME + '/.setup/ansible-macos-backup' }}"
    version: "{{ backup_repo_version }}"
